In [2]:
from pyspark.sql import SparkSession
from pyspark.ml.clustering import KMeans

In [3]:
spark = SparkSession.builder.appName("Clustering_Funds_Sharpe").getOrCreate()

In [4]:
portfolio_yield_window_path = '/data/core/fince/data/portfolioOptimization/portfolio_yield_window/'
portfolio_yield_df = spark.read.parquet(portfolio_yield_window_path)
portfolio_yield_df.limit(5).toPandas()

,SCOTIAG,AXESCP,BMERGOB,BMRGOB25,VALUEF4,BLKDIA7,BLKGUB1,GBMGUBL,INVEXGU,NTEGUB13,...,FINDE1400,ACTIGOB401,AXESMP402,HSBCMP405,INVEXMP407,NAFFP28,PRINFMP410,PRINMAS411,VECTMD414,operation_date
0,0.000404,0.000149,0.000422,0.000405,0.000347,0.000412,0.000407,0.000404,0.000348,0.000200,...,0.000140,0.000203,0.000154,0.000168,0.000172,0.000159,0.000132,0.000056,0.000170,2019-08-07
1,0.000108,0.000043,0.000114,0.000118,0.000061,0.000106,0.000093,0.000076,0.000077,0.000102,...,0.000259,0.000111,0.000243,0.000196,0.000094,0.000066,0.000128,0.000209,0.000109,2016-09-29
2,0.000104,0.000064,0.000103,0.000303,0.000060,0.000090,0.000177,0.000060,0.000062,0.000088,...,-0.000103,0.000094,0.000109,0.000046,0.000063,0.000052,0.000094,-0.000026,0.000053,2016-04-08
3,0.000191,0.000146,0.000213,0.000147,0.000171,0.000205,0.000205,0.000202,0.000175,0.000201,...,0.000365,0.000201,0.000163,0.000200,0.000174,0.000214,0.000584,0.000454,0.000258,2019-07-03
4,0.000194,0.000153,0.000205,0.000223,0.000173,0.000205,0.000205,0.000203,0.000178,0.000202,...,0.000198,0.000176,0.000166,0.000175,0.000180,0.000151,0.000198,0.000205,0.000173,2018-09-20